version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - TZ=Etc/GMT+3
      - DB_HOST=db
      - REDIS_HOST=redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: olaclick_db
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'